---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent
  labels:
    app.kubernetes.io/name: ado-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ado-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ado-agent
    spec:
      containers:
        - name: ado-agent
          image: andreswebs/azure-pipelines-agent:latest
          env:
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_URL
              valueFrom:
                secretKeyRef:
                  name: ado-agent
                  key: AGENT_URL
            - name: AGENT_POOL
              valueFrom:
                secretKeyRef:
                  name: ado-agent
                  key: AGENT_POOL
            - name: AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ado-agent
                  key: AGENT_TOKEN
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
